version: "3.8"

services:
  web:
    build:
      context: .
    container_name: fastapi_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env  
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env               

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    container_name: celery_worker
    command: ["celery", "-A", "app.tasks", "worker", "--loglevel=info"]
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env    
    depends_on:
      - redis
    env_file:
      - .env                 

